package uno;

enum GameMove {
    PLAY_CARD,
    DRAW_CARD,
    DRAW_TWO,
    SKIP,
    REVERSE,
    CHANGE_COLOR,
    DRAW_FOUR,
    DRAW_FOUR_CHALLENGE_FAIL,
    DRAW_FOUR_CHALLENGE_SUCCESS,
    CALL_UNO,
    CHALLENGE_UNO
}
